### ISSUE TITLE
Remove lumatijev:semantic-ui-beta from atmosphere?

### ISSUE THREAD

**Issue by splendido** [lumatijev/meteor-semantic-ui-beta#1]
Hello @lumatijev!

Do you agree it might be worth removing the package from atmosphere?

See the 'Removing your package` section in the [Publishing](https://atmospherejs.com/i/publishing) page.
This is to keep our project folder as clean as possible and let new developers find packages at the first attempt.

Thanks,
Luca

**Comment by lumatijev** [comment]
Hello,

sure I'll do that as soon as I get home today.

**Comment by lumatijev** [comment]
Just unmigrated package.

**Comment by splendido** [comment]
Thanks! :+1:

Have a nice day,
Luca
